name: todo
description: A simple todo list app using https://jsonplaceholder.typicode.com

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  hive_flutter: ^1.1.0
  http: ^0.13.6
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
